[build]
  command = "npm run build"
  publish = "dist"
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/api/qr-codes/*"
  to = "/.netlify/functions/serve-qr-code/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
